// Header alias mapping for subrogation Excel parsing
// Maps various possible header names to canonical field names
export const HEADER_ALIAS_MAP = {
    remarks: "cedant_remarks",
    keterangan_nama_tertanggung_cabang: "cedant_remarks",
    "keterangan / nama tertanggung / cabang": "cedant_remarks",
    no_claim_asli: "claim_no",
    claimno: "claim_no",
    claim_no: "claim_no",
    policyno: "policy_no",
    policy_no: "policy_no",
    share: "original_share_pct",
    af: "contract_id",
    treaty_or_af_code: "contract_id",
    sum_of_subrogasi: "subrogation_amount",
    subrogation_amount: "subrogation_amount",
    tugu: "gross_tugu_amount",
    fee_tugu: "fee_tugu_amount",
    share_tugu: "net_tugu_share",
    transferred_subrogation_amount: "transferred_subrogation_amount",
    pelimpahan_subro: "transferred_subrogation_amount",
    expense_fee_tugu: "expense_fee_amount",
    expense_fee: "expense_fee_amount",
    dol: "dol_date",
    bdo_klaim: "bdo_claim_date",
    bdo_claim_date: "bdo_claim_date",
    bdo_premi: "bdo_premium_date",
    bdo_premium_date: "bdo_premium_date",
    remarks_brins: "brins_remarks",
    brins_remarks: "brins_remarks",
};

export const SUBROGATION_TEMPLATE_HEADERS = [
    "Remarks",
    "No Claim Asli",
    "policyno",
    "AF",
    "Sum of Subrogasi",
    "Share",
    "Tugu",
    "Fee Tugu",
    "Share Tugu",
    "Transferred Subrogation Amount",
    "expense fee(Tugu)",
    "DOL",
    "Bdo Klaim",
    "Bdo Premi",
    "Remarks Brins",
];

export const SUBROGATION_TEMPLATE_SAMPLE = [
    [
        "BRI BANDUNG A.H. NASUTION",
        "811514102300078",
        "1115141020000418-000015",
        "AF-2020-3M",
        "-5,037,107.76",
        "1.123595506",
        "-3,056,223",
        "-458,433",
        "-2,597,789",
        "-2,597,789",
        "-2,439,318",
        "29-Dec-22",
        "Mar-23",
        "Jul-20",
        "dol 29 dec 2022, bdo klaim mar 2023, bdo premi jul 2020",
    ],
    [
        "BRI BANGKINANG",
        "811514102300002",
        "1115141021000045-000930",
        "AF-2020-3M",
        "-737,587.58",
        "1.123595506",
        "-447,525",
        "-67,129",
        "-380,396",
        "-380,396",
        "-357,191",
        "31-Jul-22",
        "Mar-23",
        "Dec-20",
        "dol 31 jul 2022, bdo klaim mar 2023, bdo premi mar 2022",
    ],
];